const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const primaryColor = args[0] || '#14b8a6';
const secondaryColor = args[1] || null;
const tertiaryColor = args[2] || null;
const themeName = args[3] || 'custom';

function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16)
  } : null;
}

function rgbToHex(r, g, b) {
  return '#' + [r, g, b].map(x => {
    const hex = Math.max(0, Math.min(255, Math.round(x))).toString(16);
    return hex.length === 1 ? '0' + hex : hex;
  }).join('');
}

function hexToHsl(hex) {
  const rgb = hexToRgb(hex);
  if (!rgb) return null;

  let r = rgb.r / 255;
  let g = rgb.g / 255;
  let b = rgb.b / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);

    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
    else if (max === g) h = ((b - r) / d + 2) / 6;
    else h = ((r - g) / d + 4) / 6;
  }

  return { h: Math.round(h * 360), s: Math.round(s * 100), l: Math.round(l * 100) };
}

function hslToHex(h, s, l) {
  h = h / 360;
  s = s / 100;
  l = l / 100;

  let r, g, b;

  if (s === 0) {
    r = g = b = l;
  } else {
    const hue2rgb = (p, q, t) => {
      if (t < 0) t += 1;
      if (t > 1) t -= 1;
      if (t < 1 / 6) return p + (q - p) * 6 * t;
      if (t < 1 / 2) return q;
      if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
      return p;
    };

    const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
    const p = 2 * l - q;
    r = hue2rgb(p, q, h + 1 / 3);
    g = hue2rgb(p, q, h);
    b = hue2rgb(p, q, h - 1 / 3);
  }

  return rgbToHex(Math.round(r * 255), Math.round(g * 255), Math.round(b * 255));
}

function generateHslScale(hexColor, steps = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]) {
  const hsl = hexToHsl(hexColor);
  if (!hsl) return {};

  const { h, s: baseS, l: baseL } = hsl;
  const baseIndex = steps.indexOf(500);

  const scale = {};

  steps.forEach((step, index) => {
    if (step === 500) {
      scale[step] = hexColor.toLowerCase();
      return;
    }

    let newS, newL;

    if (step < 500) {
      const t = (baseIndex - index) / baseIndex;
      newS = Math.round(baseS * (1 - t * 0.88));
      newL = Math.min(98, Math.round(baseL + (100 - baseL) * t * 0.9 + 4));
    } else {
      const t = (index - baseIndex) / (steps.length - 1 - baseIndex);
      newS = Math.min(100, Math.round(baseS * (1 + t * 0.14)));
      newL = Math.max(5, Math.round(baseL - baseL * t * 0.9));
    }

    scale[step] = hslToHex(h, newS, newL);
  });

  return scale;
}

function generateMultiThemeTokens(primaryColor, secondaryColor, tertiaryColor) {
  const result = { primary: generateHslScale(primaryColor) };

  if (secondaryColor) {
    result.secondary = generateHslScale(secondaryColor);
  }

  if (tertiaryColor) {
    result.tertiary = generateHslScale(tertiaryColor);
  }

  result.gray = generateHslScale('#6B7280');
  result.success = generateHslScale('#10B981');
  result.warning = generateHslScale('#F59E0B');
  result.error = generateHslScale('#EF4444');
  result.info = generateHslScale('#3B82F6');

  return result;
}

function generateCSSVariables(tokens, themeName) {
  let css = `/* Theme: ${themeName} */\n`;
  css += `/* Generated by generate-tokens.js */\n`;
  css += `/* HSL algorithm: hue-stable, lightness/saturation only */\n\n`;
  css += `:root {\n`;

  css += `  /* === Primary Scale === */\n`;
  Object.entries(tokens.primary).forEach(([step, value]) => {
    css += `  --primary-${step}: ${value};\n`;
  });

  if (tokens.secondary) {
    css += `\n  /* === Secondary Scale === */\n`;
    Object.entries(tokens.secondary).forEach(([step, value]) => {
      css += `  --secondary-${step}: ${value};\n`;
    });
  }

  if (tokens.tertiary) {
    css += `\n  /* === Tertiary Scale === */\n`;
    Object.entries(tokens.tertiary).forEach(([step, value]) => {
      css += `  --tertiary-${step}: ${value};\n`;
    });
  }

  css += `\n  /* === Gray Scale === */\n`;
  Object.entries(tokens.gray).forEach(([step, value]) => {
    css += `  --gray-${step}: ${value};\n`;
  });

  css += `\n  /* === Semantic Colors === */\n`;
  css += `  --color-primary: var(--primary-500, ${tokens.primary[500]});\n`;
  if (tokens.secondary) {
    css += `  --color-secondary: var(--secondary-500, ${tokens.secondary[500]});\n`;
  }
  if (tokens.tertiary) {
    css += `  --color-tertiary: var(--tertiary-500, ${tokens.tertiary[500]});\n`;
  }
  css += `  --color-success: var(--success-500, ${tokens.success[500]});\n`;
  css += `  --color-warning: var(--warning-500, ${tokens.warning[500]});\n`;
  css += `  --color-error: var(--error-500, ${tokens.error[500]});\n`;
  css += `  --color-info: var(--info-500, ${tokens.info[500]});\n`;

  css += `\n  /* === Font Sizes (static rpx, no calc) === */\n`;
  const fontSizes = { '2xs': 20, 'xs': 24, 'sm': 26, 'md': 28, 'lg': 30, 'xl': 32, '2xl': 40, '3xl': 48 };
  Object.entries(fontSizes).forEach(([size, value]) => {
    css += `  --font-${size}: ${value}rpx;\n`;
  });

  css += `\n  /* === Spacing (static rpx, no calc) === */\n`;
  const spacing = { 0: 0, 1: 4, 2: 8, 3: 12, 4: 16, 5: 20, 6: 24, 7: 28, 8: 32, 10: 40, 12: 48, 14: 56, 16: 64, 20: 80, 24: 96 };
  Object.entries(spacing).forEach(([size, value]) => {
    css += `  --space-${size}: ${value}rpx;\n`;
  });

  css += `\n  /* === Radius (static rpx, no calc) === */\n`;
  const radius = { none: 0, sm: 8, md: 16, lg: 24, xl: 32, full: 9999 };
  Object.entries(radius).forEach(([size, value]) => {
    css += `  --radius-${size}: ${value}rpx;\n`;
  });

  css += `\n  /* === Heights (static rpx, no calc) === */\n`;
  const heights = { 'btn-sm': 56, 'btn-md': 72, 'btn-lg': 88 };
  Object.entries(heights).forEach(([size, value]) => {
    css += `  --height-btn-${size}: ${value}rpx;\n`;
  });

  css += `\n  /* === Icons (static rpx, no calc) === */\n`;
  const icons = { xs: 24, sm: 36, md: 48, lg: 72, xl: 96 };
  Object.entries(icons).forEach(([size, value]) => {
    css += `  --icon-${size}: ${value}rpx;\n`;
  });

  css += `\n  /* === Composite Variables === */\n`;
  css += `  --radius-btn: var(--radius-full, 9999rpx);\n`;
  css += `  --radius-input: var(--radius-md, 16rpx);\n`;
  css += `  --radius-card: var(--radius-lg, 24rpx);\n`;
  css += `  --radius-tag: var(--radius-sm, 8rpx);\n`;
  css += `  --radius-image: var(--radius-sm, 8rpx);\n`;
  css += `  --radius-avatar: var(--radius-full, 9999rpx);\n`;

  css += `}\n`;
  return css;
}

function main() {
  console.log(`Generating theme tokens`);
  console.log(`  Primary: ${primaryColor}`);
  if (secondaryColor) console.log(`  Secondary: ${secondaryColor}`);
  if (tertiaryColor) console.log(`  Tertiary: ${tertiaryColor}`);
  console.log(`  Theme: ${themeName}`);
  console.log('');

  const tokens = generateMultiThemeTokens(primaryColor, secondaryColor, tertiaryColor);
  const css = generateCSSVariables(tokens, themeName);

  const outputDir = path.join(__dirname, '..', 'src', 'static', 'css');
  const outputFile = path.join(outputDir, 'base.css');

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(outputFile, css);

  console.log(`Written: ${outputFile}`);
  console.log('');
  console.log(`Usage:`);
  console.log(`  node generate-tokens.js #6366F1`);
  console.log(`  node generate-tokens.js #14b8a6 #6366f1 #f59e0b mytheme`);
}

main();